//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db1 : DbContext
    {
        public Db1()
            : base("name=Db1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Firm> Firms { get; set; }
        public virtual DbSet<tbl_Head> tbl_Head { get; set; }
        public virtual DbSet<tbl_Ledger> tbl_Ledger { get; set; }
        public virtual DbSet<tbl_MHead> tbl_MHead { get; set; }
        public virtual DbSet<tbl_Party> tbl_Party { get; set; }
        public virtual DbSet<tbl_PartyCateg> tbl_PartyCateg { get; set; }
        public virtual DbSet<tbl_PartyType> tbl_PartyType { get; set; }
    }
}
