//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Party
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Party()
        {
            this.tbl_Ledger = new HashSet<tbl_Ledger>();
        }
    
        public int PartyNameID { get; set; }
        public Nullable<int> STaxPID { get; set; }
        public string PartyName { get; set; }
        public string City { get; set; }
        public Nullable<double> Debit { get; set; }
        public Nullable<double> Credit { get; set; }
        public int PartyTypeID { get; set; }
        public string Dealer { get; set; }
        public string UrduName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Expired { get; set; }
        public Nullable<byte> firmid { get; set; }
        public byte[] ts { get; set; }
        public string GSTNO { get; set; }
        public Nullable<int> GreyID { get; set; }
        public string PartyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ledger> tbl_Ledger { get; set; }
        public virtual tbl_PartyType tbl_PartyType { get; set; }
    }
}
