//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PartyCateg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PartyCateg()
        {
            this.tbl_PartyType = new HashSet<tbl_PartyType>();
        }
    
        public int PartyCategID { get; set; }
        public string PartyCateg { get; set; }
        public Nullable<short> HeadID { get; set; }
    
        public virtual tbl_Head tbl_Head { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PartyType> tbl_PartyType { get; set; }
    }
}
