//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ledger
    {
        public int ID { get; set; }
        public int VocNo { get; set; }
        public int SrNo { get; set; }
        public System.DateTime Date { get; set; }
        public string TType { get; set; }
        public Nullable<int> PartyRef { get; set; }
        public int PartyID { get; set; }
        public string Description { get; set; }
        public Nullable<int> NetDebit { get; set; }
        public Nullable<int> NetCredit { get; set; }
        public Nullable<int> pVocNo { get; set; }
        public Nullable<int> VRef { get; set; }
        public Nullable<int> CashAC { get; set; }
        public byte firmID { get; set; }
        public bool IsPosted { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual tbl_Party tbl_Party { get; set; }
    }
}
